# 核心配置
server:
  host: '0.0.0.0'   # 监听地址，0.0.0.0 表示监听所有地址
  port: 3000        # 监听端口
  prefix: '/api'     # API 路由前缀

# 数据库配置
database:
  type: 'sqlite'    # 数据库类型: sqlite, mongodb, postgresql
  path: './data/yumeri.db' # SQLite 数据库路径

# 日志配置
logger:
  level: 'info'     # 日志级别: trace, debug, info, warn, error, fatal

# 中间件配置 (示例)
middleware:
  cors:             # CORS 配置
    origin: '*'     # 允许所有来源
    methods: 'GET,HEAD,PUT,POST,DELETE,PATCH'
    credentials: true

# 插件配置
plugins:
  - './plugins/yumeri-plugin-server' # 本地插件路径

# 鉴权配置 (示例)
auth:
  jwtSecret: 'your-secret-key' # JWT 密钥

# 监控配置 (示例)
monitoring:
  enabled: true
  port: 9000